sudo: false
language: rust
rust:
    - stable
    - beta
    - nightly
before_script:
    - pip install 'travis-cargo>=0.1.0,<0.2.0' --user
    - pip install 'CppHeaderParser>=2.7.2,<3.0.0' --user
    - export PATH="$HOME/.local/bin:$PATH"
    - git clone https://github.com/Manishearth/rust-clippy.git
    - cd rust-clippy
    - travis-cargo --only nightly build
    - export CLIPPY_PATH="$PWD/target/debug"
    - cd ..
script:
    - travis-cargo build
    - travis-cargo --only nightly rustc --lib -- -L "$CLIPPY_PATH" -l clippy -Z extra-plugins=clippy -Z no-trans
    - travis-cargo --only nightly rustc --bin cheddar -- -L "$CLIPPY_PATH" -l clippy -Z extra-plugins=clippy -Z no-trans
    - travis-cargo test
    - travis-cargo --only stable doc
after_success:
    - travis-cargo --only stable doc-upload
env:
    global:
        - RUST_BACKTRACE=1
        - TRAVIS_CARGO_NIGHTLY_FEATURE=""
        - secure: YuwS9ftMEvRBZJOTD2go5tK4hjp2nuY1kXeagyJG+vOmcuVPNGirKeEx0JsZIHo5Z7TJIJYvYPntUrxcvTVGEHuN5oeFa00t24ngdNhcuYh1+BulwSHy7k9RAFKnNCi6+GluTEBxVguP7Hdvm07q6Q0S66lK/atX0fTLeDS971MsvOiS896e9E2aU7gMmuY7eTNYWzix0YbiiP3c3SMu8/shhrU3whG3Wi0dZJ/iPlfVLdlksDaWuihJZVMRc7yVN+KV4d0tg9fwb0bo7y2OQvjGK8VUhvZx5xcpSFjiYqOy3+1jPX/EUaGd+OGINP8dRWVuH6ulR6FEX+yo0LtnoDZGRV8Bf+OjZHim3jupLJncnCDfmmqmixh6WWdRwOhbRuDFUOSaahJtDkif4TT20mV/oFt+7diAAs5BxCZR5xyAAWS8DVQDeIHXgcQFMXD6uuOpEDCDj3TVJqdaLJkbf+8U3rl9CHZVaAJpdWWDI7dOo8FVO179tq6S7Plg7Bzz5JDzDaH6fippjK4uBX6DMkQdD9fJFnH3ujvco26Q7ZmoprXzmVi6cLVydgULmcgHPpJZ7jIJWRGlQBzua0/I3ftx5Eptk9cMiYeB8kk5cDiSXvu5HGYkCExNpY23rNignQV3JMo8gIuaMXB+cbi5H4Bss1vaSksdNvHwO++CfI8=
